#!/bin/bash -l

#------ qsub option --------#
#PBS -q short-g
#PBS -l select=1
#PBS -l walltime=8:00:00
#PBS -W group_list=gj26
#PBS -j oe

source start_gpu_nodes.sh
cd ~/SAE-LEWIS

set -eo pipefail

# v5 run: v4d transform families + composition + k-draw 1-8.
# The corruption cache stays under prod_gemma_v4 (top-up, not regeneration);
# models/evals go under prod_gemma_v5 (corruption is symlinked in).
V4=./runs/prod_gemma_v4
V5=./runs/prod_gemma_v5
LLM2VEC=runs/mcgill_gemma_repro_3k/final

# 0a. Record the pre-top-up shard inventory ONCE (used to find the shards
#     generated by the new code, which carry the v4d families).
if [ ! -f "$V4/v5_pre_topup.list" ]; then
    ls "$V4/corruption"/shard-*.jsonl.gz | sort > "$V4/v5_pre_topup.list"
fi

# 0b. Top-up 500k -> 700k with the v4d code (new families, compose,
#     t_family), then move the FIRST NEW shard per worker into the dev
#     splits so selection/reporting cover the new families.
#     v5_split.done is the completion marker: corruption_parallel must not
#     re-run after shards were moved (workers would regenerate them).
if [ ! -f "$V4/v5_split.done" ]; then
    WORKERS=6 \
    OUT_DIR=$V4/corruption \
    LLM2VEC_DIR=$LLM2VEC \
    CORRUPTION_SAMPLES=700000 CORRUPTION_SHARD=2000 \
    BLOCKLIST=runs/blocklist/blocklist.npy \
    TRANSFORM_COMPOSE_PROB=0.15 \
    bash scripts/corruption_parallel.sh

    for i in 0 1 2 3 4 5; do
        new=$(comm -13 "$V4/v5_pre_topup.list" \
                  <(ls "$V4/corruption"/shard-*.jsonl.gz | sort) \
              | grep "shard-w$i-" | head -1)
        if [ -z "$new" ]; then
            echo "[v5] no new shard for worker $i — top-up incomplete?" >&2
            exit 1
        fi
        if [ "$i" = 0 ]; then
            # Rename so the new-family shard sorts FIRST in seldev: the
            # dev monitor reads the first --dev-batches sequentially.
            mv "$new" "$V4/corruption_seldev/shard-w0-00000b.jsonl.gz"
        else
            mv "$new" "$V4/corruption_dev/"
        fi
    done
    cp "$V4/corruption/meta.json" "$V4/corruption_seldev/"
    cp "$V4/corruption/meta.json" "$V4/corruption_dev/"
    touch "$V4/v5_split.done"
fi

# 1. v5 training (fresh tagger/editor; corruption + SAE cache reused).
#    DEV_BATCHES=384 spans the new-family seldev shard (2000 recs) plus
#    ~1k of the v4 shard, so best-checkpoint selection sees both.
mkdir -p "$V5"
[ -e "$V5/corruption" ] || ln -s ../prod_gemma_v4/corruption "$V5/corruption"

RUN_DIR=$V5 \
EDITOR_STEPS=100000 TAGGER_STEPS=30000 \
DEV_CORRUPTION_DIR=$V4/corruption_seldev \
DEV_BATCHES=384 \
K_DRAW=1-8 \
LLM2VEC_DIR=$LLM2VEC \
SIMCSE_DIR=$LLM2VEC \
bash scripts/run_production.sh

# 2. Evaluation at the swept operating point (k_top=8, k=8, ins 0.9;
#    confirmed on the v4 reporting dev — sweep_report.md).
python eval_tagger_editor.py \
    --corruption-dir "$V4/corruption_dev" \
    --llm2vec-dir "$LLM2VEC" \
    --tagger-ckpt "$V5/tagger/tagger-final.pt" \
    --editor-ckpt "$V5/editor/editor-final.pt" \
    --output-dir "$V5/eval_dev_k8" \
    --k-top 8 --k-amp 8 --k-sup 8 --ins-threshold 0.9 \
    --max-samples 2000 \
    --device cuda

python scripts/measure_editor_ceiling.py \
    --corruption-dir "$V4/corruption_dev" \
    --llm2vec-dir "$LLM2VEC" \
    --editor-ckpt "$V5/editor/editor-final.pt" \
    --output-dir "$V5/ceiling" \
    --max-samples 2000 \
    --device cuda

python eval_lingualens.py \
    --llm2vec-dir "$LLM2VEC" \
    --tagger-ckpt "$V5/tagger/tagger-final.pt" \
    --editor-ckpt "$V5/editor/editor-final.pt" \
    --output-dir "$V5/eval_lingualens" \
    --sae-path layer_12/width_16k/average_l0_82/params.npz \
    --k-amp 8 --k-sup 8 --ins-threshold 0.9 \
    --sample-size 100 --refine-passes 3 --refine-recompute \
    --fluency-gate 0.5 \
    --dump-details \
    --device cuda
